//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RanorexReportPortalLogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class RPSettings : global::System.Configuration.ApplicationSettingsBase {

        private static RPSettings defaultInstance = ((RPSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RPSettings())));

        public static RPSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://orangebeard-demo.praegus-solutions.com")]
        public global::System.Uri rp_endpoint
        {
            get
            {
                return ((global::System.Uri)(this["rp_endpoint"]));
            }
            set
            {
                this["rp_endpoint"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7e4b90c2-be7f-4c7d-8451-b2fa4af242fd")]
        public string rp_uuid
        {
            get
            {
                return ((string)(this["rp_uuid"]));
            }
            set
            {
                this["rp_uuid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ranorex_POC")]
        public string rp_launch
        {
            get
            {
                return ((string)(this["rp_launch"]));
            }
            set
            {
                this["rp_launch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ranorex")]
        public string rp_project
        {
            get
            {
                return ((string)(this["rp_project"]));
            }
            set
            {
                this["rp_project"] = value;
            }
        }
    }
}
